site_dir: docs
docs_dir: docsrc
site_name: Toyopuc Computer Link Python API
site_url: https://fa-yoshinobu.github.io/plc-comm-computerlink-python/
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
plugins:
  - search
  - mkdocstrings:
      default_handler: python
exclude_docs: |
  internal_docs/**
  maintainer/**
  validation/**
nav:
  - Overview: index.md
  - User Guide: user/USER_GUIDE.md
  - Model Ranges: user/MODEL_RANGES.md
  - API Reference:
      - Client: api/client.md





